### ISSUE TITLE
Docker Container Always Restarting

### ISSUE THREAD

**Issue by zxsoft** [vinbigdata-medical/vindr-lab-api#1]
I'm deploying vindr-lab using the docker way. But after created all the containers, the vinlab-api conainer was the only one who are always restarting. Then I checked the logs using command:

docker logs vinlab-api -f

And is said:

> goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:32:29 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:32:29 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]
>
>goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:32:34 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:32:34 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]
>
>goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:32:41 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:32:41 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]
>
>goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:32:55 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:32:55 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]
>
>goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:33:22 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:33:22 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]
>
>goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:34:15 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:34:15 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]
>
>goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:35:16 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:35:16 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]
>
>goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:36:17 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:36:17 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]
>
>goroutine 1 [running]:
main.main()
	/opt/app/main.go:101 +0x56e
2021/04/14 06:37:18 [INFO] [main.go:75] API is running in [production] mode
2021/04/14 06:37:18 [INFO] [main.go:96] ["http://vinlab-es:9200"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbb0e]

So, Please help me, How can I fix this Issue and start the vinlab-api service correctly?

**Comment by zxsoft** [comment]
I tried to fix the problem myself, so I started with to build the docker image myself.

But when I used the command:

docker build . -t vindr/vinlab-api:fix01

It said:

>Sending build context to Docker daemon  47.21MB
Step 1/28 : FROM golang:1.15.2 AS build
 ---> 279be524ea74
Step 2/28 : RUN mkdir /opt/app
 ---> Using cache
 ---> adcac8071c01
Step 3/28 : WORKDIR /opt/app
 ---> Using cache
 ---> 7a3790f61d5e
Step 4/28 : COPY ./go.mod ./go.mod
 ---> Using cache
 ---> eeee24a363bc
Step 5/28 : RUN go mod download
 ---> Running in ddf4c48bf73c
Removing intermediate container ddf4c48bf73c
 ---> 9849d9da8ca6
Step 6/28 : COPY ./*.go ./
 ---> 95ae5ab1ff1b
Step 7/28 : COPY ./account ./account
 ---> 3e16b67ae663
Step 8/28 : COPY ./annotation ./annotation
 ---> 3ade4c1549be
Step 9/28 : COPY ./constants ./constants
 ---> 36801871b149
Step 10/28 : COPY ./entities ./entities
 ---> ef134db3589b
Step 11/28 : COPY ./helper ./helper
 ---> e9c7efc8143b
Step 12/28 : COPY ./keycloak ./keycloak
 ---> a998840b1425
Step 13/28 : COPY ./stats ./stats
 ---> c5df139e4cd8
Step 14/28 : COPY ./label_group ./label_group
 ---> c253fb90601f
Step 15/28 : COPY ./mw ./mw
 ---> 0854e9754f96
Step 16/28 : COPY ./object ./object
 ---> 4d25d10583fc
Step 17/28 : COPY ./project ./project
 ---> a2e9f4332051
Step 18/28 : COPY ./study ./study
 ---> 09611a8ea101
Step 19/28 : COPY ./utils ./utils
 ---> 076807ea24d3
Step 20/28 : COPY ./session ./session
 ---> eef2999fa70f
Step 21/28 : RUN go build -o bin main.go
 ---> Running in 14d424efc312
> \# vindr-lab-api/study
study/task_api.go:30:103: undefined: object
study/task_api.go:35:3: unknown field 'objectStore' in struct literal of type TaskAPI
study/task_api.go:38:3: unknown field 'labelStore' in struct literal of type TaskAPI
study/task_api.go:47:59: app.CreateTaskV2 undefined (type *TaskAPI has no field or method CreateTaskV2)
study/task_api.go:386:23: app.labelStore undefined (type *TaskAPI has no field or method labelStore)
study/task_api.go:388:60: app.objectStore undefined (type *TaskAPI has no field or method objectStore)
study/task_api.go:394:78: app.objectStore undefined (type *TaskAPI has no field or method objectStore)
study/task_api.go:448:78: undefined: object
The command '/bin/sh -c go build -o bin main.go' returned a non-zero code: 2

So I can't get it done. Would you please help me to find out wether there is something wrong in source code?

**Comment by iamatsundere** [comment]
I've made an update on commit [32c67f2](https://github.com/vinbigdata-medical/vindr-lab-api/commit/32c67f28ae547d1657d13df17f8f3bdf99bd7e26), please check it!

**Comment by iamatsundere** [comment]
No more replies. Close the issue.
